### ISSUE TITLE
Blank page instead of download file

### ISSUE THREAD

**Issue by johappel** [dfactoryplugins/download-attachments#1]
I installed download-attachments in a new wordpress instance. The are no other plugins. theme ist twentyfiveteen.

I added some attachments to my post. So long all things fine. But on the frond-end post page the links to the attachments are like this:
http://example.com/wp-content/plugins/download-attachments/includes/download.php?id=9

So I got a blank page.

If a enable "pretty urls" in the plugins option page, all things are fine.

**Comment by bartoszarendt** [comment]
Can you go to plugin folder/includes/download.php and remove this line:
if ( ! defined( 'ABSPATH' ) )
	exit;
Then check again.

**Comment by bartoszarendt** [comment]
Solved in 1.2.6
