### ISSUE TITLE
How can I add the download link manually in the single post

### ISSUE THREAD

**Issue by Hujjat** [dfactoryplugins/download-attachments#4]
Hi,

It's listed in the feature list that we can add the download manually in our post. But I could not find how to do that in the doc. 

Thanks.

**Comment by bartoszarendt** [comment]
You have an icon for this in each post edit screen WYSIWYG  editor.

But you can also do a shortcode [download-attachment id="your attachment id"  title="link title"] or use a function da_download_attachment_link( $attachment_id )

**Comment by Hujjat** [comment]
Thank's for your help 👍 :)
